/**
 * Canonical player names and IDs from Arsenals.csv (single source of truth).
 * Data is generated by scripts/generate_canonical_players_ts.py.
 */

import {
  CANONICAL_BY_PLAYER_ID,
  CANONICAL_BY_SLUG,
  SLUG_TO_HAND,
} from "./canonicalPlayersData";

/** "Trafton OBrien" -> "obrien_trafton"; "O'Brien, Trafton" -> "obrien_trafton" */
function parseToSlug(raw: string): string {
  const trimmed = raw.trim().replace(/'/g, "");
  if (trimmed.includes(",")) {
    const parts = trimmed.split(",").map((s) =>
      s.replace(/[^a-zA-Z]/g, "").trim().toLowerCase()
    );
    if (parts.length >= 2 && parts[0] && parts[1]) {
      return `${parts[0]}_${parts[1]}`;
    }
  }
  const cleaned = trimmed.replace(/[^a-zA-Z\s]/g, "").trim();
  const parts = cleaned.split(/\s+/).filter(Boolean);
  if (parts.length < 2) return (parts[0] ?? "").toLowerCase();
  const first = parts[0].toLowerCase();
  const last = parts[parts.length - 1].toLowerCase();
  return `${last}_${first}`;
}

/**
 * Get canonical display name for a player (sync).
 * Accepts slug (obrien_trafton), playerId (TOBrien1), or raw (OBrien, Trafton).
 * Returns Arsenals format "Trafton OBrien" or fallback formatted string.
 */
export function getCanonicalName(slugOrPlayerIdOrRaw: string): string {
  const key = slugOrPlayerIdOrRaw.trim();

  const byId = CANONICAL_BY_PLAYER_ID[key];
  if (byId) return byId;

  const bySlug = CANONICAL_BY_SLUG[key];
  if (bySlug) return bySlug;

  const parsedSlug = parseToSlug(key);
  const byParsed = CANONICAL_BY_SLUG[parsedSlug];
  if (byParsed) return byParsed;

  if (key.includes(",")) {
    const [last, first] = key.split(",").map((s) => s.trim());
    if (first && last) return `${first} ${last}`;
  }
  return key;
}

/** Get handedness (R/L) from slug, or null if unknown. */
export function getHand(slug: string): "R" | "L" | null {
  const h = SLUG_TO_HAND[slug.trim()] ?? SLUG_TO_HAND[parseToSlug(slug)];
  return h ?? null;
}

/** Get canonical playerId (TOBrien1) from slug (obrien_trafton), or null. */
export function getCanonicalPlayerId(slug: string): string | null {
  const name = CANONICAL_BY_SLUG[slug.trim()] ?? CANONICAL_BY_SLUG[parseToSlug(slug)];
  if (!name) return null;
  for (const [pid, n] of Object.entries(CANONICAL_BY_PLAYER_ID)) {
    if (n === name) return pid;
  }
  return null;
}
