// AUTO-GENERATED from Arsenals.csv — do not edit
// Run: python3 scripts/generate_canonical_players_ts.py

export const CANONICAL_BY_PLAYER_ID: Record<string, string> = {
  "ALaPierre1": "Anthony LaPierre",
  "BBurk1": "Bobby Burk",
  "BShapiro1": "Brennan Shapiro",
  "BValente1": "Ben Valente",
  "CBurrows1": "Chase Burrows",
  "CChou1": "Colin Chou",
  "CDoan1": "Connor Doan",
  "CGrindle1": "Cam Grindle",
  "CPlace1": "Cal Place",
  "CSmith1": "Cooper Smith",
  "DJames1": "Dillon James",
  "DSnyder1": "Drew Snyder",
  "GVyse1": "Graydon Vyse",
  "JCarrea1": "Joe Carrea",
  "JClark1": "James Clark",
  "JFinkelstein1": "Jason Finkelstein",
  "JGetchell1": "Jacob Getchell",
  "MCamardi1": "Michael Camardi",
  "PRhodes1": "Pat Rhodes",
  "QOKeefe1": "Quinn OKeefe",
  "SLangan1": "Shane Langan",
  "SNoone1": "Sean Noone",
  "TFlack1": "TJ Flack",
  "TOBrien1": "Trafton OBrien",
  "TPearl1": "Tristan Pearl",
  "VPurpura1": "Vinnie Purpura",
  "ZTeator1": "Zander Teator",
};

export const CANONICAL_BY_SLUG: Record<string, string> = {
  "burk_bobby": "Bobby Burk",
  "burrows_chase": "Chase Burrows",
  "camardi_michael": "Michael Camardi",
  "carrea_joe": "Joe Carrea",
  "chou_colin": "Colin Chou",
  "clark_james": "James Clark",
  "doan_connor": "Connor Doan",
  "finkelstein_jason": "Jason Finkelstein",
  "flack_tj": "TJ Flack",
  "getchell_jacob": "Jacob Getchell",
  "grindle_cam": "Cam Grindle",
  "james_dillon": "Dillon James",
  "langan_shane": "Shane Langan",
  "lapierre_anthony": "Anthony LaPierre",
  "noone_sean": "Sean Noone",
  "obrien_trafton": "Trafton OBrien",
  "okeefe_quinn": "Quinn OKeefe",
  "pearl_tristan": "Tristan Pearl",
  "place_cal": "Cal Place",
  "purpura_vinnie": "Vinnie Purpura",
  "rhodes_pat": "Pat Rhodes",
  "shapiro_brennan": "Brennan Shapiro",
  "smith_cooper": "Cooper Smith",
  "snyder_drew": "Drew Snyder",
  "teator_zander": "Zander Teator",
  "valente_ben": "Ben Valente",
  "vyse_graydon": "Graydon Vyse",
};

export const SLUG_BY_PLAYER_ID: Record<string, string> = {
  "ALaPierre1": "lapierre_anthony",
  "BBurk1": "burk_bobby",
  "BShapiro1": "shapiro_brennan",
  "BValente1": "valente_ben",
  "CBurrows1": "burrows_chase",
  "CChou1": "chou_colin",
  "CDoan1": "doan_connor",
  "CGrindle1": "grindle_cam",
  "CPlace1": "place_cal",
  "CSmith1": "smith_cooper",
  "DJames1": "james_dillon",
  "DSnyder1": "snyder_drew",
  "GVyse1": "vyse_graydon",
  "JCarrea1": "carrea_joe",
  "JClark1": "clark_james",
  "JFinkelstein1": "finkelstein_jason",
  "JGetchell1": "getchell_jacob",
  "MCamardi1": "camardi_michael",
  "PRhodes1": "rhodes_pat",
  "QOKeefe1": "okeefe_quinn",
  "SLangan1": "langan_shane",
  "SNoone1": "noone_sean",
  "TFlack1": "flack_tj",
  "TOBrien1": "obrien_trafton",
  "TPearl1": "pearl_tristan",
  "VPurpura1": "purpura_vinnie",
  "ZTeator1": "teator_zander",
};

export const PLAYER_ID_BY_SLUG: Record<string, string> = {
  "burk_bobby": "BBurk1",
  "burrows_chase": "CBurrows1",
  "camardi_michael": "MCamardi1",
  "carrea_joe": "JCarrea1",
  "chou_colin": "CChou1",
  "clark_james": "JClark1",
  "doan_connor": "CDoan1",
  "finkelstein_jason": "JFinkelstein1",
  "flack_tj": "TFlack1",
  "getchell_jacob": "JGetchell1",
  "grindle_cam": "CGrindle1",
  "james_dillon": "DJames1",
  "langan_shane": "SLangan1",
  "lapierre_anthony": "ALaPierre1",
  "noone_sean": "SNoone1",
  "obrien_trafton": "TOBrien1",
  "okeefe_quinn": "QOKeefe1",
  "pearl_tristan": "TPearl1",
  "place_cal": "CPlace1",
  "purpura_vinnie": "VPurpura1",
  "rhodes_pat": "PRhodes1",
  "shapiro_brennan": "BShapiro1",
  "smith_cooper": "CSmith1",
  "snyder_drew": "DSnyder1",
  "teator_zander": "ZTeator1",
  "valente_ben": "BValente1",
  "vyse_graydon": "GVyse1",
};

export const PLAYER_ID_BY_ALIAS: Record<string, string> = {
  "alapierre": "ALaPierre1",
  "alapierre1": "ALaPierre1",
  "anthony": "ALaPierre1",
  "anthonylapierre": "ALaPierre1",
  "bburk": "BBurk1",
  "bburk1": "BBurk1",
  "ben": "BValente1",
  "benvalente": "BValente1",
  "bobby": "BBurk1",
  "bobbyburk": "BBurk1",
  "brennan": "BShapiro1",
  "brennanshapiro": "BShapiro1",
  "bshapiro": "BShapiro1",
  "bshapiro1": "BShapiro1",
  "burk": "BBurk1",
  "burkb": "BBurk1",
  "burkbobby": "BBurk1",
  "burrows": "CBurrows1",
  "burrowsc": "CBurrows1",
  "burrowschase": "CBurrows1",
  "bvalente": "BValente1",
  "bvalente1": "BValente1",
  "cal": "CPlace1",
  "calplace": "CPlace1",
  "cam": "CGrindle1",
  "camardi": "MCamardi1",
  "camardim": "MCamardi1",
  "camardimichael": "MCamardi1",
  "camgrindle": "CGrindle1",
  "carrea": "JCarrea1",
  "carreaj": "JCarrea1",
  "carreajoe": "JCarrea1",
  "cburrows": "CBurrows1",
  "cburrows1": "CBurrows1",
  "cchou": "CChou1",
  "cchou1": "CChou1",
  "cdoan": "CDoan1",
  "cdoan1": "CDoan1",
  "cgrindle": "CGrindle1",
  "cgrindle1": "CGrindle1",
  "chase": "CBurrows1",
  "chaseburrows": "CBurrows1",
  "chou": "CChou1",
  "chouc": "CChou1",
  "choucolin": "CChou1",
  "clark": "JClark1",
  "clarkj": "JClark1",
  "clarkjames": "JClark1",
  "colin": "CChou1",
  "colinchou": "CChou1",
  "connor": "CDoan1",
  "connordoan": "CDoan1",
  "cooper": "CSmith1",
  "coopersmith": "CSmith1",
  "cplace": "CPlace1",
  "cplace1": "CPlace1",
  "csmith": "CSmith1",
  "csmith1": "CSmith1",
  "dillon": "DJames1",
  "dillonjames": "DJames1",
  "djames": "DJames1",
  "djames1": "DJames1",
  "doan": "CDoan1",
  "doanc": "CDoan1",
  "doanconnor": "CDoan1",
  "drew": "DSnyder1",
  "drewsnyder": "DSnyder1",
  "dsnyder": "DSnyder1",
  "dsnyder1": "DSnyder1",
  "finkelstein": "JFinkelstein1",
  "finkelsteinj": "JFinkelstein1",
  "finkelsteinjason": "JFinkelstein1",
  "flack": "TFlack1",
  "flackt": "TFlack1",
  "flacktj": "TFlack1",
  "getchell": "JGetchell1",
  "getchellj": "JGetchell1",
  "getchelljacob": "JGetchell1",
  "graydon": "GVyse1",
  "graydonvyse": "GVyse1",
  "grindle": "CGrindle1",
  "grindlec": "CGrindle1",
  "grindlecam": "CGrindle1",
  "gvyse": "GVyse1",
  "gvyse1": "GVyse1",
  "jacob": "JGetchell1",
  "jacobgetchell": "JGetchell1",
  "jamesclark": "JClark1",
  "jamesd": "DJames1",
  "jamesdillon": "DJames1",
  "jason": "JFinkelstein1",
  "jasonfinkelstein": "JFinkelstein1",
  "jcarrea": "JCarrea1",
  "jcarrea1": "JCarrea1",
  "jclark": "JClark1",
  "jclark1": "JClark1",
  "jfinkelstein": "JFinkelstein1",
  "jfinkelstein1": "JFinkelstein1",
  "jgetchell": "JGetchell1",
  "jgetchell1": "JGetchell1",
  "joe": "JCarrea1",
  "joecarrea": "JCarrea1",
  "langan": "SLangan1",
  "langans": "SLangan1",
  "langanshane": "SLangan1",
  "lapierre": "ALaPierre1",
  "lapierrea": "ALaPierre1",
  "lapierreanthony": "ALaPierre1",
  "mcamardi": "MCamardi1",
  "mcamardi1": "MCamardi1",
  "michael": "MCamardi1",
  "michaelcamardi": "MCamardi1",
  "noone": "SNoone1",
  "noones": "SNoone1",
  "noonesean": "SNoone1",
  "obrien": "TOBrien1",
  "obrient": "TOBrien1",
  "obrientrafton": "TOBrien1",
  "okeefe": "QOKeefe1",
  "okeefeq": "QOKeefe1",
  "okeefequinn": "QOKeefe1",
  "pat": "PRhodes1",
  "patrhodes": "PRhodes1",
  "pearl": "TPearl1",
  "pearlt": "TPearl1",
  "pearltristan": "TPearl1",
  "place": "CPlace1",
  "placec": "CPlace1",
  "placecal": "CPlace1",
  "prhodes": "PRhodes1",
  "prhodes1": "PRhodes1",
  "purpura": "VPurpura1",
  "purpurav": "VPurpura1",
  "purpuravinnie": "VPurpura1",
  "qokeefe": "QOKeefe1",
  "qokeefe1": "QOKeefe1",
  "quinn": "QOKeefe1",
  "quinnokeefe": "QOKeefe1",
  "rhodes": "PRhodes1",
  "rhodesp": "PRhodes1",
  "rhodespat": "PRhodes1",
  "sean": "SNoone1",
  "seannoone": "SNoone1",
  "shane": "SLangan1",
  "shanelangan": "SLangan1",
  "shapiro": "BShapiro1",
  "shapirob": "BShapiro1",
  "shapirobrennan": "BShapiro1",
  "slangan": "SLangan1",
  "slangan1": "SLangan1",
  "smith": "CSmith1",
  "smithc": "CSmith1",
  "smithcooper": "CSmith1",
  "snoone": "SNoone1",
  "snoone1": "SNoone1",
  "snyder": "DSnyder1",
  "snyderd": "DSnyder1",
  "snyderdrew": "DSnyder1",
  "teator": "ZTeator1",
  "teatorz": "ZTeator1",
  "teatorzander": "ZTeator1",
  "tflack": "TFlack1",
  "tflack1": "TFlack1",
  "tj": "TFlack1",
  "tjflack": "TFlack1",
  "tobrien": "TOBrien1",
  "tobrien1": "TOBrien1",
  "tpearl": "TPearl1",
  "tpearl1": "TPearl1",
  "trafton": "TOBrien1",
  "traftonobrien": "TOBrien1",
  "tristan": "TPearl1",
  "tristanpearl": "TPearl1",
  "valente": "BValente1",
  "valenteb": "BValente1",
  "valenteben": "BValente1",
  "vinnie": "VPurpura1",
  "vinniepurpura": "VPurpura1",
  "vpurpura": "VPurpura1",
  "vpurpura1": "VPurpura1",
  "vyse": "GVyse1",
  "vyseg": "GVyse1",
  "vysegraydon": "GVyse1",
  "zander": "ZTeator1",
  "zanderteator": "ZTeator1",
  "zteator": "ZTeator1",
  "zteator1": "ZTeator1",
};

export const SLUG_TO_HAND: Record<string, "R" | "L"> = {
  "burk_bobby": "R",
  "burrows_chase": "L",
  "camardi_michael": "L",
  "carrea_joe": "R",
  "chou_colin": "R",
  "clark_james": "R",
  "doan_connor": "R",
  "finkelstein_jason": "R",
  "flack_tj": "R",
  "getchell_jacob": "R",
  "grindle_cam": "R",
  "james_dillon": "R",
  "langan_shane": "R",
  "lapierre_anthony": "R",
  "noone_sean": "R",
  "obrien_trafton": "R",
  "okeefe_quinn": "R",
  "pearl_tristan": "L",
  "place_cal": "R",
  "purpura_vinnie": "L",
  "rhodes_pat": "R",
  "shapiro_brennan": "R",
  "smith_cooper": "L",
  "snyder_drew": "L",
  "teator_zander": "R",
  "valente_ben": "R",
  "vyse_graydon": "R",
};

export const HAND_BY_PLAYER_ID: Record<string, "R" | "L"> = {
  "ALaPierre1": "R",
  "BBurk1": "R",
  "BShapiro1": "R",
  "BValente1": "R",
  "CBurrows1": "L",
  "CChou1": "R",
  "CDoan1": "R",
  "CGrindle1": "R",
  "CPlace1": "R",
  "CSmith1": "L",
  "DJames1": "R",
  "DSnyder1": "L",
  "GVyse1": "R",
  "JCarrea1": "R",
  "JClark1": "R",
  "JFinkelstein1": "R",
  "JGetchell1": "R",
  "MCamardi1": "L",
  "PRhodes1": "R",
  "QOKeefe1": "R",
  "SLangan1": "R",
  "SNoone1": "R",
  "TFlack1": "R",
  "TOBrien1": "R",
  "TPearl1": "L",
  "VPurpura1": "L",
  "ZTeator1": "R",
};
