/**
 * Canonical player names and IDs from Arsenals.csv (single source of truth).
 * Data is generated by scripts/generate_canonical_players_ts.py.
 */

import {
  CANONICAL_BY_PLAYER_ID,
  HAND_BY_PLAYER_ID,
  PLAYER_ID_BY_ALIAS,
  PLAYER_ID_BY_SLUG,
  SLUG_BY_PLAYER_ID,
} from "./canonicalPlayersData";

/** "Trafton OBrien" -> "obrien_trafton"; "O'Brien, Trafton" -> "obrien_trafton" */
function parseToSlug(raw: string): string {
  const trimmed = raw.trim().replace(/'/g, "");
  if (trimmed.includes(",")) {
    const parts = trimmed.split(",").map((s) =>
      s.replace(/[^a-zA-Z]/g, "").trim().toLowerCase()
    );
    if (parts.length >= 2 && parts[0] && parts[1]) {
      return `${parts[0]}_${parts[1]}`;
    }
  }
  const cleaned = trimmed.replace(/[^a-zA-Z\s]/g, "").trim();
  const parts = cleaned.split(/\s+/).filter(Boolean);
  if (parts.length < 2) return (parts[0] ?? "").toLowerCase();
  const first = parts[0].toLowerCase();
  const last = parts[parts.length - 1].toLowerCase();
  return `${last}_${first}`;
}

function normalizePlayerAlias(raw: string): string {
  return raw.trim().toLowerCase().replace(/[^a-z0-9]+/g, "");
}

function resolveCanonicalPlayerId(raw: string): string | null {
  const key = raw.trim();
  if (!key) return null;
  if (CANONICAL_BY_PLAYER_ID[key]) return key;
  const exactSlugMatch = PLAYER_ID_BY_SLUG[key.toLowerCase()];
  if (exactSlugMatch) return exactSlugMatch;
  const parsedSlugMatch = PLAYER_ID_BY_SLUG[parseToSlug(key)];
  if (parsedSlugMatch) return parsedSlugMatch;
  return PLAYER_ID_BY_ALIAS[normalizePlayerAlias(key)] ?? null;
}

/**
 * Get canonical display name for a player (sync).
 * Accepts slug (obrien_trafton), playerId (TOBrien1), or raw (OBrien, Trafton).
 * Returns Arsenals format "Trafton OBrien" or fallback formatted string.
 */
export function getCanonicalName(slugOrPlayerIdOrRaw: string): string {
  const key = slugOrPlayerIdOrRaw.trim();
  const playerId = resolveCanonicalPlayerId(key);
  if (playerId) return CANONICAL_BY_PLAYER_ID[playerId];

  if (key.includes(",")) {
    const [last, first] = key.split(",").map((s) => s.trim());
    if (first && last) return `${first} ${last}`;
  }
  return key;
}

/** Get handedness (R/L) from slug, or null if unknown. */
export function getHand(slug: string): "R" | "L" | null {
  const playerId = resolveCanonicalPlayerId(slug);
  if (!playerId) return null;
  return HAND_BY_PLAYER_ID[playerId] ?? null;
}

/** Get canonical playerId (TOBrien1) from slug (obrien_trafton), or null. */
export function getCanonicalPlayerId(slug: string): string | null {
  return resolveCanonicalPlayerId(slug);
}

/** Get canonical slug (obrien_trafton) from playerId (TOBrien1), or null. */
export function getSlugForPlayerId(playerId: string): string | null {
  const resolvedId = resolveCanonicalPlayerId(playerId);
  if (!resolvedId) return null;
  if (SLUG_BY_PLAYER_ID[resolvedId]) return SLUG_BY_PLAYER_ID[resolvedId];
  if (CANONICAL_BY_PLAYER_ID[resolvedId]) {
    return parseToSlug(CANONICAL_BY_PLAYER_ID[resolvedId]);
  }
  return null;
}
