// AUTO-GENERATED from Arsenals.csv — do not edit
// Run: python3 scripts/generate_canonical_players_ts.py

export const CANONICAL_BY_PLAYER_ID: Record<string, string> = {
  "ALaPierre1": "Anthony LaPierre",
  "BBurk1": "Bobby Burk",
  "BShapiro1": "Brennan Shapiro",
  "BValente1": "Ben Valente",
  "CBurrows1": "Chase Burrows",
  "CChou1": "Colin Chou",
  "CDoan1": "Connor Doan",
  "CGrindle1": "Cam Grindle",
  "CPlace1": "Cal Place",
  "CSmith1": "Cooper Smith",
  "DJames1": "Dillon James",
  "DSnyder1": "Drew Snyder",
  "GVyse1": "Graydon Vyse",
  "JCarrea1": "Joe Carrea",
  "JClark1": "James Clark",
  "JFinkelstein1": "Jason Finkelstein",
  "JGetchell1": "Jacob Getchell",
  "MCamardi1": "Michael Camardi",
  "PRhodes1": "Pat Rhodes",
  "QOKeefe1": "Quinn OKeefe",
  "SLangan1": "Shane Langan",
  "SNoone1": "Sean Noone",
  "TFlack1": "TJ Flack",
  "TOBrien1": "Trafton OBrien",
  "TPearl1": "Tristan Pearl",
  "VPurpura1": "Vinnie Purpura",
  "ZTeator1": "Zander Teator",
};

export const CANONICAL_BY_SLUG: Record<string, string> = {
  "burk_bobby": "Bobby Burk",
  "burrows_chase": "Chase Burrows",
  "camardi_michael": "Michael Camardi",
  "carrea_joe": "Joe Carrea",
  "chou_colin": "Colin Chou",
  "clark_james": "James Clark",
  "doan_connor": "Connor Doan",
  "finkelstein_jason": "Jason Finkelstein",
  "flack_tj": "TJ Flack",
  "getchell_jacob": "Jacob Getchell",
  "grindle_cam": "Cam Grindle",
  "james_dillon": "Dillon James",
  "langan_shane": "Shane Langan",
  "lapierre_anthony": "Anthony LaPierre",
  "noone_sean": "Sean Noone",
  "obrien_trafton": "Trafton OBrien",
  "okeefe_quinn": "Quinn OKeefe",
  "pearl_tristan": "Tristan Pearl",
  "place_cal": "Cal Place",
  "purpura_vinnie": "Vinnie Purpura",
  "rhodes_pat": "Pat Rhodes",
  "shapiro_brennan": "Brennan Shapiro",
  "smith_cooper": "Cooper Smith",
  "snyder_drew": "Drew Snyder",
  "teator_zander": "Zander Teator",
  "valente_ben": "Ben Valente",
  "vyse_graydon": "Graydon Vyse",
};

export const SLUG_TO_HAND: Record<string, "R" | "L"> = {
  "burk_bobby": "R",
  "burrows_chase": "L",
  "camardi_michael": "L",
  "carrea_joe": "R",
  "chou_colin": "R",
  "clark_james": "R",
  "doan_connor": "R",
  "finkelstein_jason": "R",
  "flack_tj": "R",
  "getchell_jacob": "R",
  "grindle_cam": "R",
  "james_dillon": "R",
  "langan_shane": "R",
  "lapierre_anthony": "R",
  "noone_sean": "R",
  "obrien_trafton": "R",
  "okeefe_quinn": "R",
  "pearl_tristan": "L",
  "place_cal": "R",
  "purpura_vinnie": "L",
  "rhodes_pat": "R",
  "shapiro_brennan": "R",
  "smith_cooper": "L",
  "snyder_drew": "L",
  "teator_zander": "R",
  "valente_ben": "R",
  "vyse_graydon": "R",
};
