// AUTO-GENERATED from Arsenals.csv + hitter roster — do not edit
// Run: python3 scripts/generate_canonical_players_ts.py

export const CANONICAL_BY_PLAYER_ID: Record<string, string> = {
  "ALaPierre1": "Anthony LaPierre",
  "AWilson1": "Alexander Wilson",
  "BBurk1": "Bobby Burk",
  "BReid1": "Bourke Reid",
  "BSaft1": "Brooks Saft",
  "BShapiro1": "Brennan Shapiro",
  "BValente1": "Ben Valente",
  "CBurrows1": "Chase Burrows",
  "CChou1": "Colin Chou",
  "CDoan1": "Connor Doan",
  "CFrickey1": "Connor Frickey",
  "CGrindle1": "Cam Grindle",
  "CPlace1": "Cal Place",
  "CSmith1": "Cooper Smith",
  "DDAvanzo1": "Dante DAvanzo",
  "DDrazka1": "Dylan Drazka",
  "DJames1": "Dillon James",
  "DSnyder1": "Drew Snyder",
  "GClarke1": "Griffin Clarke",
  "GCushner1": "Gabe Cushner",
  "GHarmon1": "Gabe Harmon",
  "GVyse1": "Graydon Vyse",
  "ILaforest1": "Ian Laforest",
  "JCarrea1": "Joe Carrea",
  "JClark1": "James Clark",
  "JFinkelstein1": "Jason Finkelstein",
  "JGetchell1": "Jacob Getchell",
  "JHerrera1": "Julian Herrera",
  "JLabrador1": "Jayson Labrador",
  "JMoses1": "Jack Moses",
  "JSchildcrout1": "Joshua Schildcrout",
  "MCamardi1": "Michael Camardi",
  "MMcCarthy1": "Michael McCarthy",
  "OStephens1": "Owen Stephens",
  "PRhodes1": "Pat Rhodes",
  "QOKeefe1": "Quinn OKeefe",
  "RChristensen1": "Bobby Christensen",
  "RGrace1": "Ryan Grace",
  "RHvozdovic1": "Ryan Hvozdovic",
  "RLiss1": "Ryan Liss",
  "SLangan1": "Shane Langan",
  "SNoone1": "Sean Noone",
  "TFlack1": "TJ Flack",
  "TOBrien1": "Trafton OBrien",
  "TPearl1": "Tristan Pearl",
  "VPurpura1": "Vinnie Purpura",
  "WMiller1": "Wyatt Miller",
  "ZTeator1": "Zander Teator",
};

export const CANONICAL_BY_SLUG: Record<string, string> = {
  "burk_bobby": "Bobby Burk",
  "burrows_chase": "Chase Burrows",
  "camardi_michael": "Michael Camardi",
  "carrea_joe": "Joe Carrea",
  "chou_colin": "Colin Chou",
  "christensen_bobby": "Bobby Christensen",
  "christensen_robert": "Bobby Christensen",
  "clark_james": "James Clark",
  "clarke_griffin": "Griffin Clarke",
  "cushner_gabe": "Gabe Cushner",
  "davanzo_dante": "Dante DAvanzo",
  "doan_connor": "Connor Doan",
  "drazka_dylan": "Dylan Drazka",
  "finkelstein_jason": "Jason Finkelstein",
  "flack_tj": "TJ Flack",
  "frickey_connor": "Connor Frickey",
  "getchell_jacob": "Jacob Getchell",
  "grace_ryan": "Ryan Grace",
  "grindle_cam": "Cam Grindle",
  "harmon_gabe": "Gabe Harmon",
  "herrera_julian": "Julian Herrera",
  "hvozdovic_ryan": "Ryan Hvozdovic",
  "james_dillon": "Dillon James",
  "labrador_jayson": "Jayson Labrador",
  "laforest_ian": "Ian Laforest",
  "langan_shane": "Shane Langan",
  "lapierre_anthony": "Anthony LaPierre",
  "liss_ryan": "Ryan Liss",
  "mccarthy_michael": "Michael McCarthy",
  "miller_wyatt": "Wyatt Miller",
  "moses_jack": "Jack Moses",
  "noone_sean": "Sean Noone",
  "obrien_trafton": "Trafton OBrien",
  "okeefe_quinn": "Quinn OKeefe",
  "pearl_tristan": "Tristan Pearl",
  "place_cal": "Cal Place",
  "purpura_vinnie": "Vinnie Purpura",
  "reid_bourke": "Bourke Reid",
  "rhodes_pat": "Pat Rhodes",
  "saft_brooks": "Brooks Saft",
  "schildcrout_joshua": "Joshua Schildcrout",
  "shapiro_brennan": "Brennan Shapiro",
  "smith_cooper": "Cooper Smith",
  "snyder_drew": "Drew Snyder",
  "stephens_owen": "Owen Stephens",
  "teator_zander": "Zander Teator",
  "valente_ben": "Ben Valente",
  "vyse_graydon": "Graydon Vyse",
  "wilson_alexander": "Alexander Wilson",
};

export const SLUG_BY_PLAYER_ID: Record<string, string> = {
  "ALaPierre1": "lapierre_anthony",
  "AWilson1": "wilson_alexander",
  "BBurk1": "burk_bobby",
  "BReid1": "reid_bourke",
  "BSaft1": "saft_brooks",
  "BShapiro1": "shapiro_brennan",
  "BValente1": "valente_ben",
  "CBurrows1": "burrows_chase",
  "CChou1": "chou_colin",
  "CDoan1": "doan_connor",
  "CFrickey1": "frickey_connor",
  "CGrindle1": "grindle_cam",
  "CPlace1": "place_cal",
  "CSmith1": "smith_cooper",
  "DDAvanzo1": "davanzo_dante",
  "DDrazka1": "drazka_dylan",
  "DJames1": "james_dillon",
  "DSnyder1": "snyder_drew",
  "GClarke1": "clarke_griffin",
  "GCushner1": "cushner_gabe",
  "GHarmon1": "harmon_gabe",
  "GVyse1": "vyse_graydon",
  "ILaforest1": "laforest_ian",
  "JCarrea1": "carrea_joe",
  "JClark1": "clark_james",
  "JFinkelstein1": "finkelstein_jason",
  "JGetchell1": "getchell_jacob",
  "JHerrera1": "herrera_julian",
  "JLabrador1": "labrador_jayson",
  "JMoses1": "moses_jack",
  "JSchildcrout1": "schildcrout_joshua",
  "MCamardi1": "camardi_michael",
  "MMcCarthy1": "mccarthy_michael",
  "OStephens1": "stephens_owen",
  "PRhodes1": "rhodes_pat",
  "QOKeefe1": "okeefe_quinn",
  "RChristensen1": "christensen_bobby",
  "RGrace1": "grace_ryan",
  "RHvozdovic1": "hvozdovic_ryan",
  "RLiss1": "liss_ryan",
  "SLangan1": "langan_shane",
  "SNoone1": "noone_sean",
  "TFlack1": "flack_tj",
  "TOBrien1": "obrien_trafton",
  "TPearl1": "pearl_tristan",
  "VPurpura1": "purpura_vinnie",
  "WMiller1": "miller_wyatt",
  "ZTeator1": "teator_zander",
};

export const PLAYER_ID_BY_SLUG: Record<string, string> = {
  "burk_bobby": "BBurk1",
  "burrows_chase": "CBurrows1",
  "camardi_michael": "MCamardi1",
  "carrea_joe": "JCarrea1",
  "chou_colin": "CChou1",
  "christensen_bobby": "RChristensen1",
  "christensen_robert": "RChristensen1",
  "clark_james": "JClark1",
  "clarke_griffin": "GClarke1",
  "cushner_gabe": "GCushner1",
  "davanzo_dante": "DDAvanzo1",
  "doan_connor": "CDoan1",
  "drazka_dylan": "DDrazka1",
  "finkelstein_jason": "JFinkelstein1",
  "flack_tj": "TFlack1",
  "frickey_connor": "CFrickey1",
  "getchell_jacob": "JGetchell1",
  "grace_ryan": "RGrace1",
  "grindle_cam": "CGrindle1",
  "harmon_gabe": "GHarmon1",
  "herrera_julian": "JHerrera1",
  "hvozdovic_ryan": "RHvozdovic1",
  "james_dillon": "DJames1",
  "labrador_jayson": "JLabrador1",
  "laforest_ian": "ILaforest1",
  "langan_shane": "SLangan1",
  "lapierre_anthony": "ALaPierre1",
  "liss_ryan": "RLiss1",
  "mccarthy_michael": "MMcCarthy1",
  "miller_wyatt": "WMiller1",
  "moses_jack": "JMoses1",
  "noone_sean": "SNoone1",
  "obrien_trafton": "TOBrien1",
  "okeefe_quinn": "QOKeefe1",
  "pearl_tristan": "TPearl1",
  "place_cal": "CPlace1",
  "purpura_vinnie": "VPurpura1",
  "reid_bourke": "BReid1",
  "rhodes_pat": "PRhodes1",
  "saft_brooks": "BSaft1",
  "schildcrout_joshua": "JSchildcrout1",
  "shapiro_brennan": "BShapiro1",
  "smith_cooper": "CSmith1",
  "snyder_drew": "DSnyder1",
  "stephens_owen": "OStephens1",
  "teator_zander": "ZTeator1",
  "valente_ben": "BValente1",
  "vyse_graydon": "GVyse1",
  "wilson_alexander": "AWilson1",
};

export const PLAYER_ID_BY_ALIAS: Record<string, string> = {
  "alapierre": "ALaPierre1",
  "alapierre1": "ALaPierre1",
  "alexander": "AWilson1",
  "alexanderwilson": "AWilson1",
  "anthony": "ALaPierre1",
  "anthonylapierre": "ALaPierre1",
  "awilson": "AWilson1",
  "awilson1": "AWilson1",
  "bburk": "BBurk1",
  "bburk1": "BBurk1",
  "ben": "BValente1",
  "benvalente": "BValente1",
  "bobby": "BBurk1",
  "bobbyburk": "BBurk1",
  "bourke": "BReid1",
  "bourkereid": "BReid1",
  "brennan": "BShapiro1",
  "brennanshapiro": "BShapiro1",
  "breid": "BReid1",
  "breid1": "BReid1",
  "brooks": "BSaft1",
  "brookssaft": "BSaft1",
  "bsaft": "BSaft1",
  "bsaft1": "BSaft1",
  "bshapiro": "BShapiro1",
  "bshapiro1": "BShapiro1",
  "burk": "BBurk1",
  "burkb": "BBurk1",
  "burkbobby": "BBurk1",
  "burrows": "CBurrows1",
  "burrowsc": "CBurrows1",
  "burrowschase": "CBurrows1",
  "bvalente": "BValente1",
  "bvalente1": "BValente1",
  "cal": "CPlace1",
  "calplace": "CPlace1",
  "cam": "CGrindle1",
  "camardi": "MCamardi1",
  "camardim": "MCamardi1",
  "camardimichael": "MCamardi1",
  "camgrindle": "CGrindle1",
  "carrea": "JCarrea1",
  "carreaj": "JCarrea1",
  "carreajoe": "JCarrea1",
  "cburrows": "CBurrows1",
  "cburrows1": "CBurrows1",
  "cchou": "CChou1",
  "cchou1": "CChou1",
  "cdoan": "CDoan1",
  "cdoan1": "CDoan1",
  "cfrickey": "CFrickey1",
  "cfrickey1": "CFrickey1",
  "cgrindle": "CGrindle1",
  "cgrindle1": "CGrindle1",
  "chase": "CBurrows1",
  "chaseburrows": "CBurrows1",
  "chou": "CChou1",
  "chouc": "CChou1",
  "choucolin": "CChou1",
  "bchristensen": "RChristensen1",
  "bobbychristensen": "RChristensen1",
  "christensen": "RChristensen1",
  "christensenbobby": "RChristensen1",
  "christensenr": "RChristensen1",
  "christensenrobert": "RChristensen1",
  "clark": "JClark1",
  "clarkj": "JClark1",
  "clarkjames": "JClark1",
  "clarke": "GClarke1",
  "clarkeg": "GClarke1",
  "clarkegriffin": "GClarke1",
  "colin": "CChou1",
  "colinchou": "CChou1",
  "connordoan": "CDoan1",
  "connorfrickey": "CFrickey1",
  "cooper": "CSmith1",
  "coopersmith": "CSmith1",
  "cplace": "CPlace1",
  "cplace1": "CPlace1",
  "csmith": "CSmith1",
  "csmith1": "CSmith1",
  "cushner": "GCushner1",
  "cushnerg": "GCushner1",
  "cushnergabe": "GCushner1",
  "dante": "DDAvanzo1",
  "dantedavanzo": "DDAvanzo1",
  "davanzo": "DDAvanzo1",
  "davanzod": "DDAvanzo1",
  "davanzodante": "DDAvanzo1",
  "ddavanzo": "DDAvanzo1",
  "ddavanzo1": "DDAvanzo1",
  "ddrazka": "DDrazka1",
  "ddrazka1": "DDrazka1",
  "dillon": "DJames1",
  "dillonjames": "DJames1",
  "djames": "DJames1",
  "djames1": "DJames1",
  "doan": "CDoan1",
  "doanc": "CDoan1",
  "doanconnor": "CDoan1",
  "drazka": "DDrazka1",
  "drazkad": "DDrazka1",
  "drazkadylan": "DDrazka1",
  "drew": "DSnyder1",
  "drewsnyder": "DSnyder1",
  "dsnyder": "DSnyder1",
  "dsnyder1": "DSnyder1",
  "dylan": "DDrazka1",
  "dylandrazka": "DDrazka1",
  "finkelstein": "JFinkelstein1",
  "finkelsteinj": "JFinkelstein1",
  "finkelsteinjason": "JFinkelstein1",
  "flack": "TFlack1",
  "flackt": "TFlack1",
  "flacktj": "TFlack1",
  "frickey": "CFrickey1",
  "frickeyc": "CFrickey1",
  "frickeyconnor": "CFrickey1",
  "gabecushner": "GCushner1",
  "gabeharmon": "GHarmon1",
  "gclarke": "GClarke1",
  "gclarke1": "GClarke1",
  "gcushner": "GCushner1",
  "gcushner1": "GCushner1",
  "getchell": "JGetchell1",
  "getchellj": "JGetchell1",
  "getchelljacob": "JGetchell1",
  "gharmon": "GHarmon1",
  "gharmon1": "GHarmon1",
  "grace": "RGrace1",
  "gracer": "RGrace1",
  "graceryan": "RGrace1",
  "graydon": "GVyse1",
  "graydonvyse": "GVyse1",
  "griffin": "GClarke1",
  "griffinclarke": "GClarke1",
  "grindle": "CGrindle1",
  "grindlec": "CGrindle1",
  "grindlecam": "CGrindle1",
  "gvyse": "GVyse1",
  "gvyse1": "GVyse1",
  "harmon": "GHarmon1",
  "harmong": "GHarmon1",
  "harmongabe": "GHarmon1",
  "herrera": "JHerrera1",
  "herreraj": "JHerrera1",
  "herrerajulian": "JHerrera1",
  "hvozdovic": "RHvozdovic1",
  "hvozdovicr": "RHvozdovic1",
  "hvozdovicryan": "RHvozdovic1",
  "ilaforest": "ILaforest1",
  "ilaforest1": "ILaforest1",
  "ian": "ILaforest1",
  "ianlaforest": "ILaforest1",
  "jack": "JMoses1",
  "jackmoses": "JMoses1",
  "jacob": "JGetchell1",
  "jacobgetchell": "JGetchell1",
  "jamesclark": "JClark1",
  "jamesd": "DJames1",
  "jamesdillon": "DJames1",
  "jason": "JFinkelstein1",
  "jasonfinkelstein": "JFinkelstein1",
  "jayson": "JLabrador1",
  "jaysonlabrador": "JLabrador1",
  "jcarrea": "JCarrea1",
  "jcarrea1": "JCarrea1",
  "jclark": "JClark1",
  "jclark1": "JClark1",
  "jfinkelstein": "JFinkelstein1",
  "jfinkelstein1": "JFinkelstein1",
  "jgetchell": "JGetchell1",
  "jgetchell1": "JGetchell1",
  "jherrera": "JHerrera1",
  "jherrera1": "JHerrera1",
  "jlabrador": "JLabrador1",
  "jlabrador1": "JLabrador1",
  "jmoses": "JMoses1",
  "jmoses1": "JMoses1",
  "joe": "JCarrea1",
  "joecarrea": "JCarrea1",
  "joshua": "JSchildcrout1",
  "joshuaschildcrout": "JSchildcrout1",
  "jschildcrout": "JSchildcrout1",
  "jschildcrout1": "JSchildcrout1",
  "julian": "JHerrera1",
  "julianherrera": "JHerrera1",
  "labrador": "JLabrador1",
  "labradorj": "JLabrador1",
  "labradorjayson": "JLabrador1",
  "laforest": "ILaforest1",
  "laforesti": "ILaforest1",
  "laforestian": "ILaforest1",
  "langan": "SLangan1",
  "langans": "SLangan1",
  "langanshane": "SLangan1",
  "lapierre": "ALaPierre1",
  "lapierrea": "ALaPierre1",
  "lapierreanthony": "ALaPierre1",
  "liss": "RLiss1",
  "lissr": "RLiss1",
  "lissryan": "RLiss1",
  "mcamardi": "MCamardi1",
  "mcamardi1": "MCamardi1",
  "mccarthy": "MMcCarthy1",
  "mccarthym": "MMcCarthy1",
  "mccarthymichael": "MMcCarthy1",
  "michaelcamardi": "MCamardi1",
  "michaelmccarthy": "MMcCarthy1",
  "miller": "WMiller1",
  "millerw": "WMiller1",
  "millerwyatt": "WMiller1",
  "mmccarthy": "MMcCarthy1",
  "mmccarthy1": "MMcCarthy1",
  "moses": "JMoses1",
  "mosesj": "JMoses1",
  "mosesjack": "JMoses1",
  "noone": "SNoone1",
  "noones": "SNoone1",
  "noonesean": "SNoone1",
  "obrien": "TOBrien1",
  "obrient": "TOBrien1",
  "obrientrafton": "TOBrien1",
  "okeefe": "QOKeefe1",
  "okeefeq": "QOKeefe1",
  "okeefequinn": "QOKeefe1",
  "ostephens": "OStephens1",
  "ostephens1": "OStephens1",
  "owen": "OStephens1",
  "owenstephens": "OStephens1",
  "pat": "PRhodes1",
  "patrhodes": "PRhodes1",
  "pearl": "TPearl1",
  "pearlt": "TPearl1",
  "pearltristan": "TPearl1",
  "place": "CPlace1",
  "placec": "CPlace1",
  "placecal": "CPlace1",
  "prhodes": "PRhodes1",
  "prhodes1": "PRhodes1",
  "purpura": "VPurpura1",
  "purpurav": "VPurpura1",
  "purpuravinnie": "VPurpura1",
  "qokeefe": "QOKeefe1",
  "qokeefe1": "QOKeefe1",
  "quinn": "QOKeefe1",
  "quinnokeefe": "QOKeefe1",
  "rchristensen": "RChristensen1",
  "rchristensen1": "RChristensen1",
  "reid": "BReid1",
  "reidb": "BReid1",
  "reidbourke": "BReid1",
  "rgrace": "RGrace1",
  "rgrace1": "RGrace1",
  "rhodes": "PRhodes1",
  "rhodesp": "PRhodes1",
  "rhodespat": "PRhodes1",
  "rhvozdovic": "RHvozdovic1",
  "rhvozdovic1": "RHvozdovic1",
  "rliss": "RLiss1",
  "rliss1": "RLiss1",
  "robert": "RChristensen1",
  "robertchristensen": "RChristensen1",
  "ryan": "RGrace1",
  "ryangrace": "RGrace1",
  "ryanhvozdovic": "RHvozdovic1",
  "ryanliss": "RLiss1",
  "saft": "BSaft1",
  "saftb": "BSaft1",
  "saftbrooks": "BSaft1",
  "schildcrout": "JSchildcrout1",
  "schildcroutj": "JSchildcrout1",
  "schildcroutjoshua": "JSchildcrout1",
  "sean": "SNoone1",
  "seannoone": "SNoone1",
  "shane": "SLangan1",
  "shanelangan": "SLangan1",
  "shapiro": "BShapiro1",
  "shapirob": "BShapiro1",
  "shapirobrennan": "BShapiro1",
  "slangan": "SLangan1",
  "slangan1": "SLangan1",
  "snoone": "SNoone1",
  "snoone1": "SNoone1",
  "snyder": "DSnyder1",
  "snyderd": "DSnyder1",
  "snyderdrew": "DSnyder1",
  "stephens": "OStephens1",
  "stephenso": "OStephens1",
  "stephensowen": "OStephens1",
  "teator": "ZTeator1",
  "teatorz": "ZTeator1",
  "teatorzander": "ZTeator1",
  "tflack": "TFlack1",
  "tflack1": "TFlack1",
  "tj": "TFlack1",
  "tjflack": "TFlack1",
  "tobrien": "TOBrien1",
  "tobrien1": "TOBrien1",
  "tpearl": "TPearl1",
  "tpearl1": "TPearl1",
  "trafton": "TOBrien1",
  "traftonobrien": "TOBrien1",
  "tristan": "TPearl1",
  "tristanpearl": "TPearl1",
  "valente": "BValente1",
  "valenteb": "BValente1",
  "valenteben": "BValente1",
  "vinnie": "VPurpura1",
  "vinniepurpura": "VPurpura1",
  "vpurpura": "VPurpura1",
  "vpurpura1": "VPurpura1",
  "vyse": "GVyse1",
  "vyseg": "GVyse1",
  "vysegraydon": "GVyse1",
  "wilson": "AWilson1",
  "wilsona": "AWilson1",
  "wilsonalexander": "AWilson1",
  "wmiller": "WMiller1",
  "wmiller1": "WMiller1",
  "wyatt": "WMiller1",
  "wyattmiller": "WMiller1",
  "zander": "ZTeator1",
  "zanderteator": "ZTeator1",
  "zteator": "ZTeator1",
  "zteator1": "ZTeator1",
};

export const SLUG_TO_HAND: Record<string, "R" | "L"> = {
  "burk_bobby": "R",
  "burrows_chase": "L",
  "camardi_michael": "L",
  "carrea_joe": "R",
  "chou_colin": "R",
  "clark_james": "R",
  "doan_connor": "R",
  "finkelstein_jason": "R",
  "flack_tj": "R",
  "getchell_jacob": "R",
  "grindle_cam": "R",
  "james_dillon": "R",
  "langan_shane": "R",
  "lapierre_anthony": "R",
  "noone_sean": "R",
  "obrien_trafton": "R",
  "okeefe_quinn": "R",
  "pearl_tristan": "L",
  "place_cal": "R",
  "purpura_vinnie": "L",
  "rhodes_pat": "R",
  "shapiro_brennan": "R",
  "smith_cooper": "L",
  "snyder_drew": "L",
  "teator_zander": "R",
  "valente_ben": "R",
  "vyse_graydon": "R",
};

export const HAND_BY_PLAYER_ID: Record<string, "R" | "L"> = {
  "ALaPierre1": "R",
  "BBurk1": "R",
  "BShapiro1": "R",
  "BValente1": "R",
  "CBurrows1": "L",
  "CChou1": "R",
  "CDoan1": "R",
  "CGrindle1": "R",
  "CPlace1": "R",
  "CSmith1": "L",
  "DJames1": "R",
  "DSnyder1": "L",
  "GVyse1": "R",
  "JCarrea1": "R",
  "JClark1": "R",
  "JFinkelstein1": "R",
  "JGetchell1": "R",
  "MCamardi1": "L",
  "PRhodes1": "R",
  "QOKeefe1": "R",
  "SLangan1": "R",
  "SNoone1": "R",
  "TFlack1": "R",
  "TOBrien1": "R",
  "TPearl1": "L",
  "VPurpura1": "L",
  "ZTeator1": "R",
};
