/**
 * MLB pitcher comp engine.
 *
 * Finds the closest MLB pitchers to a given Babson pitch profile using
 * weighted nearest-neighbor search on IVB, HB, and velocity.
 *
 * Data source: web/public/data/mlb_pitch_comps.json
 * Generated by: scripts/sync_savant_comps.py
 *
 * Sign conventions (must match Trackman):
 *   IVB: positive = upward (rising fastball = +)
 *   HB:  positive = toward 1B from catcher's perspective
 */

import { normalizePitchTypeName, type CanonPitch } from "@/lib/mlbPitchAverages";

// ---------------------------------------------------------------------------
// Types matching web/public/data/mlb_pitch_comps.json schema
// ---------------------------------------------------------------------------

export interface MLBPitch {
  pitchType: string;   // Canonical name e.g. "Fastball"
  n: number | null;    // Pitch count in Savant sample
  avgVelo: number | null;
  avgIvb: number | null;
  avgHb: number | null;
}

export interface MLBPitcher {
  pitcherId: string;
  name: string;
  hand: "R" | "L";
  pitches: MLBPitch[];
}

export interface MLBCompsData {
  year: number;
  updated: string;
  minPitches: number;
  pitchers: MLBPitcher[];
}

// ---------------------------------------------------------------------------
// Comp input / output
// ---------------------------------------------------------------------------

export interface CompInput {
  pitchType: string;   // Trackman pitch type label (will be normalized)
  ivb: number | null;
  hb: number | null;
  /** Retained for display context only — not used in distance calculation */
  velo: number | null;
}

export interface MLBCompResult {
  pitcher: {
    id: string;
    name: string;
    hand: string;
  };
  pitch: MLBPitch;
  /** Shape distance (IVB + HB only) — lower = more similar movement profile */
  distance: number;
  /** Per-metric deltas for display; velo always null (not used in matching) */
  deltas: {
    ivb: number | null;
    hb: number | null;
    velo: null;
  };
}

// ---------------------------------------------------------------------------
// Distance weights
// ---------------------------------------------------------------------------

/**
 * Shape-only matching: pure movement profile, velocity intentionally excluded.
 * Equal weight to IVB and HB so neither axis dominates.
 */
const WEIGHTS = {
  ivb: 0.5,
  hb: 0.5,
} as const;

// ---------------------------------------------------------------------------
// Core lookup
// ---------------------------------------------------------------------------

/**
 * Find the top-N MLB pitchers whose given pitch type most closely matches
 * the provided Babson pitch profile.
 *
 * @param input  - Babson pitch profile (pitchType, ivb, hb, velo)
 * @param hand   - Pitcher handedness ("R" | "L") — only same-hand comps returned
 * @param pitchers - Full MLB pitchers array from mlb_pitch_comps.json
 * @param topN   - How many comps to return (default 5)
 */
export function findPitchComps(
  input: CompInput,
  hand: "R" | "L",
  pitchers: MLBPitcher[],
  topN = 5,
): MLBCompResult[] {
  const canon = normalizePitchTypeName(input.pitchType);
  if (!canon) return [];

  const results: MLBCompResult[] = [];

  for (const pitcher of pitchers) {
    if (pitcher.hand !== hand) continue;

    // Find the matching pitch type in this pitcher's arsenal
    const match = pitcher.pitches.find(
      (p) => normalizePitchTypeName(p.pitchType) === canon,
    );
    if (!match) continue;

    const ivbDiff =
      input.ivb != null && match.avgIvb != null
        ? input.ivb - match.avgIvb
        : null;
    const hbDiff =
      input.hb != null && match.avgHb != null ? input.hb - match.avgHb : null;

    // Both IVB and HB required for a shape-based comp
    if (ivbDiff === null || hbDiff === null) continue;

    // Pure shape distance — velocity intentionally excluded
    const dist = Math.sqrt(
      WEIGHTS.ivb * ivbDiff ** 2 + WEIGHTS.hb * hbDiff ** 2,
    );

    results.push({
      pitcher: { id: pitcher.pitcherId, name: pitcher.name, hand: pitcher.hand },
      pitch: match,
      distance: Math.round(dist * 100) / 100,
      deltas: {
        ivb: Math.round(ivbDiff * 10) / 10,
        hb: Math.round(hbDiff * 10) / 10,
        velo: null,
      },
    });
  }

  results.sort((a, b) => a.distance - b.distance);
  return results.slice(0, topN);
}

// ---------------------------------------------------------------------------
// Arsenal-level comp (aggregate distance across all pitch types)
// ---------------------------------------------------------------------------

export interface ArsenalCompResult {
  pitcher: {
    id: string;
    name: string;
    hand: string;
  };
  /** Average distance across matched pitch types */
  avgDistance: number;
  /** How many pitch types were matched */
  matchedPitches: number;
  /** Per-pitch-type distances */
  pitchBreakdown: Array<{
    pitchType: string;
    distance: number;
  }>;
}

/**
 * Find the top-N MLB pitchers whose overall arsenal most closely matches
 * the provided Babson arsenal profile.
 *
 * Only pitchers who share at least `minMatchedPitches` pitch types with the
 * Babson arsenal are considered.
 */
export function findArsenalComps(
  babsonArsenal: CompInput[],
  hand: "R" | "L",
  pitchers: MLBPitcher[],
  topN = 5,
  minMatchedPitches = 1,
): ArsenalCompResult[] {
  const results: ArsenalCompResult[] = [];

  for (const pitcher of pitchers) {
    if (pitcher.hand !== hand) continue;

    const breakdown: Array<{ pitchType: string; distance: number }> = [];

    for (const input of babsonArsenal) {
      const comps = findPitchComps(input, hand, [pitcher], 1);
      if (comps.length > 0) {
        breakdown.push({
          pitchType: (normalizePitchTypeName(input.pitchType) as CanonPitch | null) ?? input.pitchType,
          distance: comps[0].distance,
        });
      }
    }

    if (breakdown.length < minMatchedPitches) continue;

    const avgDistance =
      Math.round(
        (breakdown.reduce((s, b) => s + b.distance, 0) / breakdown.length) *
          100,
      ) / 100;

    results.push({
      pitcher: { id: pitcher.pitcherId, name: pitcher.name, hand: pitcher.hand },
      avgDistance,
      matchedPitches: breakdown.length,
      pitchBreakdown: breakdown,
    });
  }

  results.sort((a, b) => a.avgDistance - b.avgDistance);
  return results.slice(0, topN);
}
