import type {
  ChartingPitch,
  ChartingPitcherSegment,
  ChartingPlateAppearance,
} from "./types";

const GAME_ID = "fix-game-001";
const SEG_A_ID = "fix-seg-A";
const SEG_B_ID = "fix-seg-B";

const segments: ChartingPitcherSegment[] = [
  {
    id: SEG_A_ID,
    gameId: GAME_ID,
    playerId: "DJames1",
    displayName: "D. James",
    teamSide: "our",
    segmentOrder: 0,
    enteredInning: 1,
    exitedInning: 5,
    runsOverride: null,
    earnedRunsOverride: null,
  },
  {
    id: SEG_B_ID,
    gameId: GAME_ID,
    playerId: "CBurrows1",
    displayName: "C. Burrows",
    teamSide: "our",
    segmentOrder: 1,
    enteredInning: 6,
    exitedInning: null,
    runsOverride: null,
    earnedRunsOverride: null,
  },
];

const plateAppearances: ChartingPlateAppearance[] = [
  {
    id: "fix-pa-A1",
    gameId: GAME_ID,
    segmentId: SEG_A_ID,
    paOrder: 0,
    inning: 1,
    isTopInning: true,
    teamSide: "opponent",
    hitterName: "Smith",
    lineupSlot: 1,
    resultCode: "K",
    buntContext: false,
    runnerOnFirst: null,
    runnerOnSecond: null,
    runnerOnThird: null,
  },
  {
    id: "fix-pa-A2",
    gameId: GAME_ID,
    segmentId: SEG_A_ID,
    paOrder: 1,
    inning: 1,
    isTopInning: true,
    teamSide: "opponent",
    hitterName: "Jones",
    lineupSlot: 2,
    resultCode: "KL",
    buntContext: false,
    runnerOnFirst: null,
    runnerOnSecond: null,
    runnerOnThird: null,
  },
  {
    id: "fix-pa-A3",
    gameId: GAME_ID,
    segmentId: SEG_A_ID,
    paOrder: 2,
    inning: 1,
    isTopInning: true,
    teamSide: "opponent",
    hitterName: "Brown",
    lineupSlot: 3,
    resultCode: "BB",
    buntContext: false,
    runnerOnFirst: null,
    runnerOnSecond: null,
    runnerOnThird: null,
  },
  {
    id: "fix-pa-A4",
    gameId: GAME_ID,
    segmentId: SEG_A_ID,
    paOrder: 3,
    inning: 2,
    isTopInning: true,
    teamSide: "opponent",
    hitterName: "Smith",
    lineupSlot: 4,
    resultCode: "1B",
    buntContext: false,
    runnerOnFirst: null,
    runnerOnSecond: null,
    runnerOnThird: null,
  },
  {
    id: "fix-pa-A5",
    gameId: GAME_ID,
    segmentId: SEG_A_ID,
    paOrder: 4,
    inning: 2,
    isTopInning: true,
    teamSide: "opponent",
    hitterName: "Taylor",
    lineupSlot: 5,
    resultCode: null,
    buntContext: false,
    runnerOnFirst: null,
    runnerOnSecond: null,
    runnerOnThird: null,
  },
  {
    id: "fix-pa-B1",
    gameId: GAME_ID,
    segmentId: SEG_B_ID,
    paOrder: 5,
    inning: 6,
    isTopInning: true,
    teamSide: "opponent",
    hitterName: "Garcia",
    lineupSlot: 6,
    resultCode: "BB",
    buntContext: false,
    runnerOnFirst: null,
    runnerOnSecond: null,
    runnerOnThird: null,
  },
  {
    id: "fix-pa-B2",
    gameId: GAME_ID,
    segmentId: SEG_B_ID,
    paOrder: 6,
    inning: 6,
    isTopInning: true,
    teamSide: "opponent",
    hitterName: "Miller",
    lineupSlot: 7,
    resultCode: "1B",
    buntContext: false,
    runnerOnFirst: null,
    runnerOnSecond: null,
    runnerOnThird: null,
  },
  {
    id: "fix-pa-B3",
    gameId: GAME_ID,
    segmentId: SEG_B_ID,
    paOrder: 7,
    inning: 7,
    isTopInning: true,
    teamSide: "opponent",
    hitterName: "Davis",
    lineupSlot: 8,
    resultCode: null,
    buntContext: false,
    runnerOnFirst: null,
    runnerOnSecond: null,
    runnerOnThird: null,
  },
];

const pitches: ChartingPitch[] = [
  {
    id: "fix-pitch-A-01",
    gameId: GAME_ID,
    paId: "fix-pa-A1",
    pitchOrder: 0,
    pitchType: "Fastball",
    locationCell: 5,
    pitchResult: "called_strike",
    ballsBefore: 0,
    strikesBefore: 0,
    velocity: null,
  },
  {
    id: "fix-pitch-A-02",
    gameId: GAME_ID,
    paId: "fix-pa-A1",
    pitchOrder: 1,
    pitchType: "Slider",
    locationCell: 12,
    pitchResult: "foul",
    ballsBefore: 0,
    strikesBefore: 1,
    velocity: null,
  },
  {
    id: "fix-pitch-A-03",
    gameId: GAME_ID,
    paId: "fix-pa-A1",
    pitchOrder: 2,
    pitchType: "Fastball",
    locationCell: 8,
    pitchResult: "swinging_strike",
    ballsBefore: 0,
    strikesBefore: 2,
    velocity: null,
  },
  {
    id: "fix-pitch-A-04",
    gameId: GAME_ID,
    paId: "fix-pa-A2",
    pitchOrder: 3,
    pitchType: "Fastball",
    locationCell: 2,
    pitchResult: "called_strike",
    ballsBefore: 0,
    strikesBefore: 0,
    velocity: null,
  },
  {
    id: "fix-pitch-A-05",
    gameId: GAME_ID,
    paId: "fix-pa-A2",
    pitchOrder: 4,
    pitchType: "Curveball",
    locationCell: 6,
    pitchResult: "ball",
    ballsBefore: 0,
    strikesBefore: 1,
    velocity: null,
  },
  {
    id: "fix-pitch-A-06",
    gameId: GAME_ID,
    paId: "fix-pa-A2",
    pitchOrder: 5,
    pitchType: "Slider",
    locationCell: 3,
    pitchResult: "called_strike",
    ballsBefore: 1,
    strikesBefore: 1,
    velocity: null,
  },
  {
    id: "fix-pitch-A-07",
    gameId: GAME_ID,
    paId: "fix-pa-A3",
    pitchOrder: 6,
    pitchType: "Fastball",
    locationCell: 11,
    pitchResult: "ball",
    ballsBefore: 0,
    strikesBefore: 0,
    velocity: null,
  },
  {
    id: "fix-pitch-A-08",
    gameId: GAME_ID,
    paId: "fix-pa-A3",
    pitchOrder: 7,
    pitchType: "Fastball",
    locationCell: null,
    pitchResult: "swinging_strike",
    ballsBefore: 1,
    strikesBefore: 0,
    velocity: null,
  },
  {
    id: "fix-pitch-A-09",
    gameId: GAME_ID,
    paId: "fix-pa-A3",
    pitchOrder: 8,
    pitchType: "Changeup",
    locationCell: 7,
    pitchResult: "called_strike",
    ballsBefore: 1,
    strikesBefore: 1,
    velocity: null,
  },
  {
    id: "fix-pitch-A-10",
    gameId: GAME_ID,
    paId: "fix-pa-A3",
    pitchOrder: 9,
    pitchType: "Slider",
    locationCell: 13,
    pitchResult: "in_play",
    ballsBefore: 1,
    strikesBefore: 2,
    velocity: null,
  },
  {
    id: "fix-pitch-A-11",
    gameId: GAME_ID,
    paId: "fix-pa-A4",
    pitchOrder: 10,
    pitchType: "Curveball",
    locationCell: 9,
    pitchResult: "bunt_foul",
    ballsBefore: 0,
    strikesBefore: 0,
    velocity: null,
  },
  {
    id: "fix-pitch-A-12",
    gameId: GAME_ID,
    paId: "fix-pa-A4",
    pitchOrder: 11,
    pitchType: "Fastball",
    locationCell: 14,
    pitchResult: "swinging_strike",
    ballsBefore: 0,
    strikesBefore: 1,
    velocity: null,
  },
  {
    id: "fix-pitch-A-13",
    gameId: GAME_ID,
    paId: "fix-pa-A4",
    pitchOrder: 12,
    pitchType: "Slider",
    locationCell: 4,
    pitchResult: "in_play",
    ballsBefore: 0,
    strikesBefore: 2,
    velocity: null,
  },
  {
    id: "fix-pitch-A-14",
    gameId: GAME_ID,
    paId: "fix-pa-A5",
    pitchOrder: 13,
    pitchType: "Fastball",
    locationCell: null,
    pitchResult: "ball",
    ballsBefore: 0,
    strikesBefore: 0,
    velocity: null,
  },
  {
    id: "fix-pitch-A-15",
    gameId: GAME_ID,
    paId: "fix-pa-A5",
    pitchOrder: 14,
    pitchType: "Fastball",
    locationCell: 1,
    pitchResult: "foul",
    ballsBefore: 1,
    strikesBefore: 0,
    velocity: null,
  },
  {
    id: "fix-pitch-B-01",
    gameId: GAME_ID,
    paId: "fix-pa-B1",
    pitchOrder: 15,
    pitchType: "Fastball",
    locationCell: null,
    pitchResult: "ball",
    ballsBefore: 0,
    strikesBefore: 0,
    velocity: null,
  },
  {
    id: "fix-pitch-B-02",
    gameId: GAME_ID,
    paId: "fix-pa-B1",
    pitchOrder: 16,
    pitchType: "Changeup",
    locationCell: null,
    pitchResult: "ball",
    ballsBefore: 1,
    strikesBefore: 0,
    velocity: null,
  },
  {
    id: "fix-pitch-B-03",
    gameId: GAME_ID,
    paId: "fix-pa-B2",
    pitchOrder: 17,
    pitchType: "Slider",
    locationCell: null,
    pitchResult: "called_strike",
    ballsBefore: 0,
    strikesBefore: 0,
    velocity: null,
  },
  {
    id: "fix-pitch-B-04",
    gameId: GAME_ID,
    paId: "fix-pa-B2",
    pitchOrder: 18,
    pitchType: "Fastball",
    locationCell: null,
    pitchResult: "in_play",
    ballsBefore: 0,
    strikesBefore: 1,
    velocity: null,
  },
  {
    id: "fix-pitch-B-05",
    gameId: GAME_ID,
    paId: "fix-pa-B3",
    pitchOrder: 19,
    pitchType: "Curveball",
    locationCell: null,
    pitchResult: "ball",
    ballsBefore: 0,
    strikesBefore: 0,
    velocity: null,
  },
  {
    id: "fix-pitch-B-06",
    gameId: GAME_ID,
    paId: "fix-pa-B3",
    pitchOrder: 20,
    pitchType: "Fastball",
    locationCell: null,
    pitchResult: "ball",
    ballsBefore: 1,
    strikesBefore: 0,
    velocity: null,
  },
];

const pasForSegA = plateAppearances.filter((pa) => pa.segmentId === SEG_A_ID);
const pasForSegB = plateAppearances.filter((pa) => pa.segmentId === SEG_B_ID);
const paIdsForSegA = new Set(pasForSegA.map((pa) => pa.id));
const paIdsForSegB = new Set(pasForSegB.map((pa) => pa.id));
const pitchesForSegA = pitches.filter((pitch) => paIdsForSegA.has(pitch.paId));
const pitchesForSegB = pitches.filter((pitch) => paIdsForSegB.has(pitch.paId));
const pasForSmith = plateAppearances.filter((pa) => pa.hitterName === "Smith");
const paIdsForSmith = new Set(pasForSmith.map((pa) => pa.id));
const pitchesForSmith = pitches.filter((pitch) => paIdsForSmith.has(pitch.paId));

export interface AnalyticsFixtureSnapshot {
  gameId: string;
  gameDate: string;
  segments: ChartingPitcherSegment[];
  pitches: ChartingPitch[];
  plateAppearances: ChartingPlateAppearance[];
  pitchesForSegA: ChartingPitch[];
  pasForSegA: ChartingPlateAppearance[];
  pitchesForSegB: ChartingPitch[];
  pasForSegB: ChartingPlateAppearance[];
  pitchesForSmith: ChartingPitch[];
  pasForSmith: ChartingPlateAppearance[];
}

// Segment A expected values:
// totalPitches: 15
// strikePct: 12 / 15 = 80.0
// whiffPct: 3 / 8 = 37.5
// zonePct: 9 / 13 = 69.2
// chasePct: 3 / 4 = 75.0
// fpsPct: 3 / 5 = 60.0
// kPct: 2 / 4 = 50.0
// bbPct: 1 / 4 = 25.0
// pitchMix: Fastball 8, Slider 4, Curveball 2, Changeup 1
export const fixtureAnalyticsSnapshot: AnalyticsFixtureSnapshot = {
  gameId: GAME_ID,
  gameDate: "2026-03-01",
  segments,
  pitches,
  plateAppearances,
  pitchesForSegA,
  pasForSegA,
  pitchesForSegB,
  pasForSegB,
  pitchesForSmith,
  pasForSmith,
};
