// Barrel re-export. All charting live-state logic is split across:
//   live-constants.ts  — PA result option arrays and PAResultType
//   live-domain.ts     — types, PA helpers, state derivation
//   live-mutations.ts  — snapshot mutation functions

export {
  GAME_PITCH_RESULTS,
  HIT_OPTIONS,
  FLY_OUT_OPTIONS,
  LINE_OUT_OPTIONS,
  POP_OUT_OPTIONS,
  GROUND_OUT_OPTIONS,
  UNASSISTED_OUT_OPTIONS,
  DOUBLE_PLAY_OPTIONS,
  ERROR_OPTIONS,
  FIELDERS_CHOICE_OPTIONS,
  BASERUNNER_OUT_OPTIONS,
  PA_RESULT_OPTIONS,
  type PAResultType,
} from "./live-constants";

export {
  type PAClosureState,
  type PAResultFamily,
  type PAPitchProgress,
  type ChartingLiveState,
  type GameStateOverride,
  type NextPASeed,
  type LiveStateOptions,
  type RecordPitchInput,
  type PAResultGroup,
  type UpdatePlateAppearanceDetailsInput,
  type UpdatePlateAppearanceContextInput,
  initialCountFromSeed,
  nextPASeedFromInitialCount,
  inferInitialCountFromPitches,
  resolvePlateAppearanceInitialCount,
  emptyBaserunnerState,
  normalizeBaserunnerState,
  baserunnerStateFromPlateAppearance,
  battingSideForMatchup,
  pitchingSideForMatchup,
  deriveNextLineupSlot,
  availablePAResultsForClosure,
  guidanceTextForClosure,
  paResultFamily,
  paResultOutsRecorded,
  detailTextForPAResult,
  closeoutResultGroups,
  isPAResultType,
  derivePAPitchProgress,
  deriveChartingLiveState,
  createGameStateOverride,
} from "./live-domain";

export {
  recordPitchInSnapshot,
  recordBaserunnerOutInSnapshot,
  switchPitcherInSnapshot,
  closeCurrentPlateAppearance,
  undoSnapshotAction,
  syncHitterToSnapshot,
  updatePitchVelocityInSnapshot,
  updatePAHitterNameInSnapshot,
  updatePlateAppearanceDetailsInSnapshot,
  updatePlateAppearanceContextInSnapshot,
  updateSnapshotRevision,
  lineupNameForSlot,
  countPitcherPitches,
  countPitcherInningPitches,
} from "./live-mutations";
